# Generated by Django 4.2.5 on 2023-09-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_type', models.CharField(max_length=50, verbose_name='news type')),
                ('price', models.IntegerField()),
                ('size', models.FloatField()),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('balcony_direction', models.CharField(blank=True, max_length=50, null=True, verbose_name='balcony direction')),
                ('legal', models.CharField(max_length=50)),
                ('width', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('bedrooms', models.IntegerField()),
                ('toilets', models.IntegerField()),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('furniture', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
