# Generated by Django 4.2.5 on 2023-09-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bds',
            name='city',
            field=models.TextField(blank=True, default='Unknown', max_length=200, null=True, verbose_name='Thành phố'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='furniture',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Nội thất'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='legal',
            field=models.TextField(blank=True, choices=[('Đã có sổ', 'Đã có sổ'), ('Đang chờ sổ', 'Đang chờ sổ'), ('Sổ hồng', 'Sổ hồng'), ('Sổ đỏ', 'Sổ đỏ'), ('Giấy tờ hợp lệ', 'Giấy tờ hợp lệ'), ('Hợp đồng mua bán', 'Hợp đồng mua bán'), ('Sổ đỏ/ Sổ hồng', 'Sổ đỏ/ Sổ hồng')], max_length=50, null=True, verbose_name='Giấy tờ pháp lý'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='location',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='news_type',
            field=models.TextField(blank=True, choices=[('Mua bán', 'Mua bán'), ('Nhà đất bán', 'Nhà đất bán'), ('Cần bán', 'Cần bán')], max_length=50, null=True, verbose_name='Loại tin'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='range_price',
            field=models.TextField(blank=True, choices=[('Nhỏ hơn 500000000', 'Nhỏ hơn 500000000'), ('Từ 500000000 đến 1000000000', 'Từ 500000000 đến 1000000000'), ('Từ 1000000000 đến 5000000000', 'Từ 1000000000 đến 5000000000'), ('Lớn hơn 5000000000', 'Lớn hơn 5000000000')], default='Nhỏ hơn 500000000', null=True, verbose_name='Khoảng giá'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='range_size',
            field=models.TextField(blank=True, choices=[('Nhỏ hơn 50', 'Nhỏ hơn 50'), ('Từ 50 đến 100', 'Từ 50 đến 100'), ('Từ 100 đến 500', 'Từ 100 đến 500'), ('Lớn hơn 500', 'Lớn hơn 500')], default='Nhỏ hơn 50', null=True, verbose_name='Khoảng diện tích'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='size',
            field=models.FloatField(blank=True, null=True, verbose_name='Diện tích (mét vuông)'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
