# Generated by Django 4.2.5 on 2023-09-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bds_balcony_direction_alter_bds_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bds',
            name='ID',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='bds',
            name='city',
            field=models.TextField(default='Unknown', max_length=200, verbose_name='Thành phố'),
        ),
        migrations.AddField(
            model_name='bds',
            name='range_price',
            field=models.FloatField(choices=[('Nhỏ hơn 500000000', 'Nhỏ hơn 500000000'), ('Từ 500000000 đến 1000000000', 'Từ 500000000 đến 1000000000'), ('Từ 1000000000 đến 5000000000', 'Từ 1000000000 đến 5000000000'), ('Lớn hơn 5000000000', 'Lớn hơn 5000000000')], default='Nhỏ hơn 500000000', verbose_name='Khoảng giá'),
        ),
        migrations.AddField(
            model_name='bds',
            name='range_size',
            field=models.FloatField(choices=[('Nhỏ hơn 50', 'Nhỏ hơn 50'), ('Từ 50 đến 100', 'Từ 50 đến 100'), ('Từ 100 đến 500', 'Từ 100 đến 500'), ('Lớn hơn 500', 'Lớn hơn 500')], default='Nhỏ hơn 50', verbose_name='Khoảng diện tích'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số phòng ngủ'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='price',
            field=models.FloatField(verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='size',
            field=models.FloatField(verbose_name='Diện tích (mét vuông)'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='toilets',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số toilets'),
        ),
    ]
