# Generated by Django 4.2.5 on 2023-09-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bds_id_bds_city_bds_range_price_bds_range_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bds',
            name='bedrooms',
            field=models.TextField(blank=True, null=True, verbose_name='Số phòng ngủ'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='floors',
            field=models.TextField(blank=True, null=True, verbose_name='Tầng'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='length',
            field=models.TextField(blank=True, null=True, verbose_name='Chiều dài'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='range_price',
            field=models.TextField(choices=[('Nhỏ hơn 500000000', 'Nhỏ hơn 500000000'), ('Từ 500000000 đến 1000000000', 'Từ 500000000 đến 1000000000'), ('Từ 1000000000 đến 5000000000', 'Từ 1000000000 đến 5000000000'), ('Lớn hơn 5000000000', 'Lớn hơn 5000000000')], default='Nhỏ hơn 500000000', verbose_name='Khoảng giá'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='range_size',
            field=models.TextField(choices=[('Nhỏ hơn 50', 'Nhỏ hơn 50'), ('Từ 50 đến 100', 'Từ 50 đến 100'), ('Từ 100 đến 500', 'Từ 100 đến 500'), ('Lớn hơn 500', 'Lớn hơn 500')], default='Nhỏ hơn 50', verbose_name='Khoảng diện tích'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='toilets',
            field=models.TextField(blank=True, null=True, verbose_name='Số toilets'),
        ),
        migrations.AlterField(
            model_name='bds',
            name='width',
            field=models.TextField(blank=True, null=True, verbose_name='Chiều ngang'),
        ),
    ]
